name: Build Shairport-Sync for OpenWRT

on:
  workflow_dispatch: # manually trigger karne ke liye

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget unzip

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.5/targets/ramips/mt76x8/openwrt-sdk-23.05.5-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.5-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-23.05.5-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64 sdk

      - name: Setup Shairport-Sync package
        run: |
          mkdir -p sdk/package/sound
          git clone https://github.com/mikebrady/shairport-sync.git
          cp -r shairport-sync openwrt-shairport-sync
          # simple OpenWRT Makefile
          mkdir -p sdk/package/sound/shairport-sync
          cat > sdk/package/sound/shairport-sync/Makefile <<'EOF'
          include $(TOPDIR)/rules.mk

          PKG_NAME:=shairport-sync
          PKG_VERSION:=4.3
          PKG_RELEASE:=1
          PKG_SOURCE_PROTO:=git
          PKG_SOURCE_URL:=https://github.com/mikebrady/shairport-sync.git
          PKG_SOURCE_VERSION:=master

          include $(INCLUDE_DIR)/package.mk

          define Package/shairport-sync
            SECTION:=sound
            CATEGORY:=Sound
            TITLE:=AirPlay 2 Shairport-Sync
            DEPENDS:=+libopenssl +libpthread +libdaemon +alsa-lib
          endef

          define Package/shairport-sync/description
            Shairport Sync with AirPlay 2 support (lightweight build).
          endef

          define Package/shairport-sync/install
            $(INSTALL_DIR) $(1)/usr/bin
            $(INSTALL_BIN) $(PKG_BUILD_DIR)/shairport-sync $(1)/usr/bin/
          endef

          $(eval $(call BuildPackage,shairport-sync))
          EOF

      - name: Build Package
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/shairport-sync/compile V=s

      - name: List build output
        run: |
          ls -R sdk/bin || true

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: shairport-sync-ipk
          path: |
            sdk/bin/packages/*/*/shairport-sync_*.ipk
            sdk/bin/packages/*/*/*/shairport-sync_*.ipk
            sdk/bin/targets/*/*/packages/shairport-sync_*.ipk